### ISSUE TITLE
[google] chef-provisioning-fog doesn't delete the disk in GCE

### ISSUE THREAD

**Issue by jjasghar** [chef/chef-provisioning-fog#166] opened 2016-02-18 21:06 UTC
It seems when i run the typical delete, the disk isn't removed.

```
14:59:58 chef-provisioning-fog > (master) bundle exec chef-client -z destroy.rb
[2016-02-18T15:00:00-06:00] INFO: Auto-discovered chef repository at /Users/jasghar/repo
[2016-02-18T15:00:01-06:00] INFO: Started chef-zero at chefzero://localhost:8889 with repository at /Users/jasghar/repo
  One version per cookbook

[2016-02-18T15:00:01-06:00] INFO: Forking chef instance to converge...
Starting Chef Client, version 12.7.2
[2016-02-18T15:00:01-06:00] INFO: *** Chef 12.7.2 ***
[2016-02-18T15:00:01-06:00] INFO: Chef-client pid: 91808
[2016-02-18T15:00:05-06:00] INFO: Run List is []
[2016-02-18T15:00:05-06:00] INFO: Run List expands to []
[2016-02-18T15:00:05-06:00] INFO: Starting Chef Run for jjasghar
[2016-02-18T15:00:05-06:00] INFO: Running start handlers
[2016-02-18T15:00:05-06:00] INFO: Start handlers complete.
[2016-02-18T15:00:05-06:00] INFO: HTTP Request Returned 404 Not Found: Object not found:
resolving cookbooks for run list: []
[2016-02-18T15:00:06-06:00] INFO: Loading cookbooks []
Synchronizing Cookbooks:
Compiling Cookbooks...
[2016-02-18T15:00:06-06:00] WARN: Node jjasghar has an empty run list.
Converging 1 resources
Recipe: @recipe_files::/Users/jasghar/repo/chef-provisioning-fog/destroy.rb
  * machine_batch[default] action destroy[2016-02-18T15:00:06-06:00] INFO: Processing machine_batch[default] action destroy (@recipe_files::/Users/jasghar/repo/chef-provisioning-fog/destroy.rb line 5)

    - [myserver] destroy machine myserver (17943672334784367058 at fog:Google:)[2016-02-18T15:00:08-06:00] INFO: Processing chef_node[myserver] action delete (basic_chef_client::block line 22)

    - [myserver] delete node myserver at chefzero://localhost:8889[2016-02-18T15:00:08-06:00] INFO: Processing chef_client[myserver] action delete (basic_chef_client::block line 26)
[2016-02-18T15:00:08-06:00] INFO: HTTP Request Returned 404 Not Found: Object not found: chefzero://localhost:8889/clients/myserver
[2016-02-18T15:00:08-06:00] INFO: Processing chef_node[myserver] action delete (basic_chef_client::block line 91)
[2016-02-18T15:00:08-06:00] INFO: HTTP Request Returned 404 Not Found: Object not found: chefzero://localhost:8889/nodes/myserver

[2016-02-18T15:00:08-06:00] INFO: Chef Run complete in 2.57393 seconds
```

Then attempting to recreate:

```
15:03:10 chef-provisioning-fog > (master) bundle exec chef-client -z google.rb
[2016-02-18T15:03:40-06:00] INFO: Auto-discovered chef repository at /Users/jasghar/repo
[2016-02-18T15:03:40-06:00] INFO: Started chef-zero at chefzero://localhost:8889 with repository at /Users/jasghar/repo
  One version per cookbook

[2016-02-18T15:03:40-06:00] INFO: Forking chef instance to converge...
Starting Chef Client, version 12.7.2
[2016-02-18T15:03:40-06:00] INFO: *** Chef 12.7.2 ***
[2016-02-18T15:03:40-06:00] INFO: Chef-client pid: 91924
[2016-02-18T15:03:45-06:00] INFO: Run List is []
[2016-02-18T15:03:45-06:00] INFO: Run List expands to []
[2016-02-18T15:03:45-06:00] INFO: Starting Chef Run for jjasghar
[2016-02-18T15:03:45-06:00] INFO: Running start handlers
[2016-02-18T15:03:45-06:00] INFO: Start handlers complete.
[2016-02-18T15:03:45-06:00] INFO: HTTP Request Returned 404 Not Found: Object not found:
resolving cookbooks for run list: []
[2016-02-18T15:03:45-06:00] INFO: Loading cookbooks []
Synchronizing Cookbooks:
Compiling Cookbooks...
[2016-02-18T15:03:45-06:00] WARN: Node jjasghar has an empty run list.
Converging 1 resources
Recipe: @recipe_files::/Users/jasghar/repo/chef-provisioning-fog/google.rb
  * machine[myserver] action converge[2016-02-18T15:03:45-06:00] INFO: Processing machine[myserver] action converge (@recipe_files::/Users/jasghar/repo/chef-provisioning-fog/google.rb line 14)
[2016-02-18T15:03:45-06:00] INFO: HTTP Request Returned 404 Not Found: Object not found: chefzero://localhost:8889/nodes/myserver


    ================================================================================
    Error executing action `converge` on resource 'machine[myserver]'
    ================================================================================

    Fog::Errors::Error
    ------------------
    The resource 'projects/tidal-pathway-119021/zones/europe-west1-d/disks/myserver' already exists

    Resource Declaration:
    ---------------------
    # In /Users/jasghar/repo/chef-provisioning-fog/google.rb

     14: machine "myserver" do
     15:   tag 'thistag'
     16: end

    Compiled Resource:
    ------------------
    # Declared in /Users/jasghar/repo/chef-provisioning-fog/google.rb:14:in `from_file'

    machine("myserver") do
      action [:converge]
      retries 0
      retry_delay 2
      default_guard_interpreter :default
      chef_server {:chef_server_url=>"chefzero://localhost:8889", :options=>{:client_name=>"jjasghar", :signing_key_filename=>"/Users/jasghar/.chef/jjasghar.pem", :api_version=>"0"}}
      driver "fog:Google"
      machine_options {:bootstrap_options=>{:image_name=>"debian-7-wheezy-v20150325", :zone_name=>"europe-west1-d", :machine_type=>"n1-standard-1"}}
      declared_type :machine
      cookbook_name "@recipe_files"
      recipe_name "/Users/jasghar/repo/chef-provisioning-fog/google.rb"
      attribute_modifiers [["tags", #<Proc:0x007fb58634da58@/Users/jasghar/.rvm/gems/ruby-2.1.8/gems/cheffish-2.0.1/lib/cheffish/node_properties.rb:39>]]
    end

[2016-02-18T15:03:49-06:00] INFO: Running queued delayed notifications before re-raising exception

Running handlers:
[2016-02-18T15:03:49-06:00] ERROR: Running exception handlers
Running handlers complete
[2016-02-18T15:03:49-06:00] ERROR: Exception handlers complete
Chef Client failed. 0 resources updated in 08 seconds
[2016-02-18T15:03:49-06:00] FATAL: Stacktrace dumped to /Users/jasghar/.chef/cache/chef-stacktrace.out
[2016-02-18T15:03:49-06:00] FATAL: Please provide the contents of the stacktrace.out file if you file a bug report
[2016-02-18T15:03:49-06:00] ERROR: machine[myserver] (@recipe_files::/Users/jasghar/repo/chef-provisioning-fog/google.rb line 14) had an error: Fog::Errors::Error: The resource 'projects/tidal-pathway-119021/zones/europe-west1-d/disks/myserver' already exists
[2016-02-18T15:03:49-06:00] FATAL: Chef::Exceptions::ChildConvergeError: Chef run process exited unsuccessfully (exit code 1)
```

Not sure if the delete or something isn't being called correctly. But this is just to track this ?bug?.

**Comment by jjasghar** [comment] 2016-02-18 23:03
@kri5 can you take a look at this too? It seems that we should be able to delete the disk if we want to. Maybe a flag to turn it on/off?

**Comment by kri5** [comment] 2016-02-18 23:11
@jjasghar i think it's the expected behaviour, as you do not want to destroy any data by default, but maybe you could use this to enable/disable this based on a flag https://github.com/fog/fog-google/blob/master/lib/fog/google/models/compute/server.rb#L165 .

I won't be able to look at this atm.

**Comment by jjasghar** [comment] 2016-02-18 23:12
Ah cool, thats more or less what i was expecting. I just wanted to double check, thanks for the info!

**Comment by tas50** [comment] 2018-08-20 21:39
I'm going to close this out since our latest release no longer supports GCE due to the broken fog support for GCE.

**Closed by tas50** 2018-08-20 21:39 UTC
